# Site settings
author: Silas Michael Knight
title: If (Taulology == Tautology)
header-img: img/home-bg.png
email: silasfelinus@gmail.com
copyright_name: Silas Michael Knight
description: > # this means to ignore newlines until "baseurl:"
  Meditations on code from a lifetime student and former clown
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  silasfelinus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
